/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#include <getopt.h>
#include <pthread.h>
#include "steque.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

/* Global Variables*/
static struct option gLongOptions[] = {
	{"nthreads",      required_argument,      NULL,           't'},           
	{NULL,            0,                      NULL,             0}
};

steque_t req_queue;
pthread_mutex_t mutex_rq = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t rq_nonEmpty = PTHREAD_COND_INITIALIZER; 

typedef union dataUnion{
		jpeg_in jpeg_minify_1_arg;
} dataUnion;

/* Defines information passed to worker thread */
typedef struct request {  
    SVCXPRT *transp;
	struct svc_req *rqstp;
	dataUnion *pData;
	xdrproc_t _xdr_argument;
	xdrproc_t _xdr_result;
} request;


/* Worker thread function */
static void *minifyHandler(void *arg){
	while(1) {  // Loops forever
        // Retrieve request
		pthread_mutex_lock(&mutex_rq);
		while (steque_isempty(&req_queue)) {
			pthread_cond_wait(&rq_nonEmpty, &mutex_rq);
		}
		request *req = (request *)steque_pop(&req_queue);
		pthread_mutex_unlock(&mutex_rq);

		// Process minify request...
		union {
		    jpeg_out jpeg_minify_1_res;
	    } result;

	    bool_t retval = jpeg_minify_1_svc(*(jpeg_in *)(req->pData), (jpeg_out *)&result, req->rqstp);

		if (retval > 0 && !svc_sendreply(req->transp, req->_xdr_result, (char *)&result)) {
		    svcerr_systemerr (req->transp);
	    }
	    if (!svc_freeargs (req->transp, req->_xdr_argument, (caddr_t)(req->pData))) {
		    fprintf (stderr, "%s", "unable to free arguments");
		    exit (1);
	    }
	    if (!jpeg_prog_1_freeresult (req->transp, req->_xdr_result, (caddr_t) &result)) {
		    fprintf (stderr, "%s", "unable to free results");
        }
	}	
}


/* Creates Worker Threads */
static void createWorkerThreads(int nthreads) {
     for (int i = 0 ; i < nthreads; i++) {
		pthread_t thread;
		pthread_create(&thread, NULL, minifyHandler, NULL);  // Any args needs to be passed in?
		pthread_detach(thread);
	}
}


static void jpeg_prog_1(struct svc_req *rqstp, register SVCXPRT *transp) {
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	dataUnion* argument = malloc(sizeof(dataUnion));

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case JPEG_MINIFY:
		_xdr_argument = (xdrproc_t) xdr_jpeg_in;
		_xdr_result = (xdrproc_t) xdr_jpeg_out;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	
	memset ((char *)argument, 0, sizeof(dataUnion));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) /*&*/argument)) {
		svcerr_decode (transp);
		return;
	}

    // Enqueue the request
	request *req = (request *)malloc(sizeof(request));
	req->transp = transp;
	req->rqstp = rqstp;
	req->pData = argument;
	req->_xdr_argument = _xdr_argument;
	req->_xdr_result = _xdr_result;

	pthread_mutex_lock(&mutex_rq);
    steque_enqueue(&req_queue, (steque_item)req);
	pthread_mutex_unlock(&mutex_rq);
	pthread_cond_broadcast(&rq_nonEmpty);

	return;
}


int main (int argc, char* argv[]) {
	int option_char = 0;
	int nthreads = 1;
    while ((option_char = getopt_long(argc, argv, "s:w:t:h", gLongOptions, NULL)) != -1) {
        switch (option_char) {
			case 't':
                nthreads = atoi(optarg);
                break;                   
	  	    default:
			    fprintf(stderr, "Unknown argument. Use -t to specify nthreads !\r\n");
				exit(1);
        }
    }

    steque_init(&req_queue);
    createWorkerThreads(nthreads);

	register SVCXPRT *transp;

	pmap_unset (JPEG_PROG, JPEG_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, JPEG_PROG, JPEG_VER, jpeg_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (JPEG_PROG, JPEG_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, JPEG_PROG, JPEG_VER, jpeg_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (JPEG_PROG, JPEG_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
