/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_FILE_SIZE 1000000000

struct jpeg_in {
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct jpeg_in jpeg_in;

struct jpeg_out {
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct jpeg_out jpeg_out;

#define JPEG_PROG 0x3654321
#define JPEG_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define JPEG_MINIFY 1
extern  enum clnt_stat jpeg_minify_1(jpeg_in , jpeg_out *, CLIENT *);
extern  bool_t jpeg_minify_1_svc(jpeg_in , jpeg_out *, struct svc_req *);
extern int jpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define JPEG_MINIFY 1
extern  enum clnt_stat jpeg_minify_1();
extern  bool_t jpeg_minify_1_svc();
extern int jpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_jpeg_in (XDR *, jpeg_in*);
extern  bool_t xdr_jpeg_out (XDR *, jpeg_out*);

#else /* K&R C */
extern bool_t xdr_jpeg_in ();
extern bool_t xdr_jpeg_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
